# Generated by Django 3.2 on 2023-09-18 12:13

import config.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_m', models.ImageField(blank=True, null=True, upload_to='photo_pages', validators=[config.validators.validate_image_size, config.validators.validate_name], verbose_name='Фон Главная')),
                ('photo_h', models.ImageField(blank=True, null=True, upload_to='photo_pages', validators=[config.validators.validate_image_size, config.validators.validate_name], verbose_name='Фон Домики')),
                ('photo_k', models.ImageField(blank=True, null=True, upload_to='photo_pages', validators=[config.validators.validate_image_size, config.validators.validate_name], verbose_name='Фон Кухня')),
                ('photo_e', models.ImageField(blank=True, null=True, upload_to='photo_pages', validators=[config.validators.validate_image_size, config.validators.validate_name], verbose_name='Фон Развлечения')),
                ('was_changed', models.DateField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Фоновые фото',
                'verbose_name_plural': 'Фоновые фото',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Заповедный остров', max_length=256, verbose_name='Название сайта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('house_title', models.CharField(default='Домики', max_length=256, verbose_name='Домики')),
                ('house_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('kitchen_title', models.CharField(default='Кухня', max_length=256, verbose_name='Кухня')),
                ('kitchen_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('entertainment_title', models.CharField(default='Развлечения', max_length=256, verbose_name='Развлечения')),
                ('entertainment_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('was_changed', models.DateField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='PolicyAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.TextField(blank=True, null=True, verbose_name='Политика конфиденциальности')),
                ('agreement', models.TextField(blank=True, null=True, verbose_name='Пользовательское соглашение')),
                ('was_changed', models.DateField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Политика и соглашение',
                'verbose_name_plural': 'Политика и соглашение',
            },
        ),
        migrations.CreateModel(
            name='PhotoMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='photo_main_page', validators=[config.validators.validate_image_size], verbose_name='Файл')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.mainpage', verbose_name='Main Page Photo')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
