# Generated by Django 3.2 on 2023-10-09 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MaxValueValidator(9999.99), django.core.validators.MinValueValidator(0.0)], verbose_name='Стоимость'),
        ),
    ]
