# Generated by Django 3.2 on 2023-10-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы'},
        ),
    ]
