# Generated by Django 3.2 on 2024-03-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_baseuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramIdUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
            ],
        ),
    ]
