# Generated by Django 3.2 on 2024-03-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_telegramiduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramiduser',
            name='telegram_id',
            field=models.IntegerField(unique=True),
        ),
    ]
