# Generated by Django 3.2 on 2024-04-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_telegramiduser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramiduser',
            name='telegram_id',
            field=models.CharField(max_length=120),
        ),
    ]
