# Generated by Django 3.2 on 2023-09-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='type',
            field=models.CharField(choices=[('sgb', 'Односпальная'), ('dbb', 'Двухспальная'), ('exb', 'Дополнительная'), ('crb', 'Детская')], max_length=40, verbose_name='Кровать'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('bedroom', 'Спальня')], max_length=20, verbose_name='Комната'),
        ),
    ]
