# Generated by Django 3.2 on 2023-10-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_auto_20230930_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='price_holiday',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Цена по выходным'),
            preserve_default=False,
        ),
    ]
