# Generated by Django 3.2 on 2023-10-09 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_alter_object_price_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='pers_num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='Вместимость'),
            preserve_default=False,
        ),
    ]
