# Generated by Django 3.2 on 2023-10-09 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0004_alter_object_pers_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='price_holiday',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MaxValueValidator(9999.99), django.core.validators.MinValueValidator(0.0)], verbose_name='Цена по выходным'),
        ),
        migrations.AlterField(
            model_name='object',
            name='price_weekday',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MaxValueValidator(9999.99), django.core.validators.MinValueValidator(0.0)], verbose_name='Цена по будням'),
        ),
        migrations.AlterField(
            model_name='objectfeature',
            name='type',
            field=models.CharField(choices=[('Продвинутые удобства', [('Wifi', 'Бесплатный Wi-Fi'), ('Free parking', 'Бесплатная парковка'), ('Terrace', 'Терасса'), ('Balcony', 'Балкон'), ('Conditioner', 'Кондиционер'), ('TV', 'Телевизор'), ('Patio', 'Патио'), ('Brazier', 'Мангал'), ('Personal pier', 'Личный пирс')]), ('Базовые удобства', [('Kitchen', 'Кухня'), ('Fridge', 'Холодильник'), ('Dishes', 'Посуда'), ('Stove', 'Плита'), ('Microwave', 'Микроволновая печь'), ('Dishwasher', 'Посудомоечная машина')]), ('Дополнительно', [('Furniture for babies', 'Мебель для грудных детей'), ('Shower/Bath', 'Душ/Ванна'), ('Washing machine', 'Стиральная машина'), ('Iron', 'Утюг'), ('Hair dryer', 'Фен')])], max_length=256, verbose_name='Тип услуги'),
        ),
    ]
