# Generated by Django 3.2 on 2024-04-19 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0005_auto_20231009_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='sex',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='count_kids',
            field=models.IntegerField(help_text='От 0 до 20', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Кол-во детей до 10 лет'),
        ),
    ]
